# platform :ios, '9.0'

target 'FanToMath' do
  
  use_frameworks!

  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'ExpandableCell'
  pod 'Kingfisher'

end
